# Generated by Django 2.2.12 on 2024-12-26 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=250, null=True)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_upd", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "classe",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_room",
                        to="school.Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon",
                "verbose_name_plural": "Salons",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("status", models.BooleanField(default=True)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateField(auto_now=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auteur_message",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salon",
                        to="chat.Salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
    ]
