# Generated by Django 2.2.12 on 2024-12-26 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instructor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
