# Generated by Django 2.2.12 on 2024-12-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_auto_20241227_0221"),
        ("student", "0002_auto_20241226_0826"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="quizzes",
            field=models.ManyToManyField(
                related_name="students", through="quiz.TakenQuiz", to="quiz.Quiz"
            ),
        ),
    ]
